### ISSUE TITLE
Why did you split sam into two different submodular?

### ISSUE THREAD

**Issue by kuazhangxiaoai** [vietanhdev/samexporter#12]
Why did you split sam into two different submodular  named encoder and decoder? What's different between decoder and encoder? Can I use SAM as single model?

Thanks for your answers.

**Comment by kknk765** [comment]
It is actually really nice that SAM is split in 2. The encoder creates a representation of the image (basically a float array). This part is very slow.
The decoder takes that representation and e.g.  a point or a box and outputs a mask. This part is fast.
So the great thing about having the encoder and decoder separately is that you can do the slow encoding once and then create multiple masks quickly by running the decoder several times with the output from the encoding but with different point/box input.

**Comment by vietanhdev** [comment]
@kknk765 Nice explaination. Thanks!! 👍👍👍
